server:
  port: 8081

spring:
  application:
    name: user-service
    security:
      jwt:
        secret-key: 744bea40aeb7d7e98966836fec34272dded0e623f24bd63ce013112a3855175c
        expiration-time: 15000

  datasource:
    url: jdbc:postgresql://localhost:5432/job_plateform
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Mehdimidou123!
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

    kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: my-group
    topic:
      account: user-events


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true